// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ivpmUoByQPajJ-QSvfrhiyHDtBjiQ5s',
    appId: '1:507552638423:web:224bd3dfd4fd4165721792',
    messagingSenderId: '507552638423',
    projectId: 'ascenity-3ed5f',
    authDomain: 'ascenity-3ed5f.firebaseapp.com',
    storageBucket: 'ascenity-3ed5f.firebasestorage.app',
    measurementId: 'G-HYRZ2SH7NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPSkJiOtIYQL_YAWuFqEsYf9BW0v0c8zk',
    appId: '1:507552638423:android:181a7309ec186514721792',
    messagingSenderId: '507552638423',
    projectId: 'ascenity-3ed5f',
    storageBucket: 'ascenity-3ed5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcpLOldq0VLdOOUlDFphY5wyVI0sEQIe0',
    appId: '1:507552638423:ios:217be02e15ec72e3721792',
    messagingSenderId: '507552638423',
    projectId: 'ascenity-3ed5f',
    storageBucket: 'ascenity-3ed5f.firebasestorage.app',
    iosClientId: '507552638423-nk6qlvmtqefk0d11pjq3n9u1u4vtaq4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ascenityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcpLOldq0VLdOOUlDFphY5wyVI0sEQIe0',
    appId: '1:507552638423:ios:217be02e15ec72e3721792',
    messagingSenderId: '507552638423',
    projectId: 'ascenity-3ed5f',
    storageBucket: 'ascenity-3ed5f.firebasestorage.app',
    iosClientId: '507552638423-nk6qlvmtqefk0d11pjq3n9u1u4vtaq4g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ascenityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ivpmUoByQPajJ-QSvfrhiyHDtBjiQ5s',
    appId: '1:507552638423:web:92634515e0670083721792',
    messagingSenderId: '507552638423',
    projectId: 'ascenity-3ed5f',
    authDomain: 'ascenity-3ed5f.firebaseapp.com',
    storageBucket: 'ascenity-3ed5f.firebasestorage.app',
    measurementId: 'G-81EB03YKXQ',
  );
}
